name: PiEmbedActions CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Shared Node.js Setup
        uses: ./.github/workflows/shared-setup.yml@2778_open_report_editor
      - name: Run js tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Shared Node.js Setup
        uses: ./.github/workflows/shared-setup.yml@2778_open_report_editor
      - name: Minify and Bundle the library
        run: npm run build
      - name: Upload minified version as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pi-embed-actions-build
          path: dist/pi-embed-actions-v1.0.0.min.js

  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Shared Node.js Setup
        uses: ./.github/workflows/shared-setup.yml@2778_open_report_editor
      - name: Generate new docs
        run: npm run generate-docs
      - name: Upload generated docs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pi-embed-actions-docs
          path: docs/