name: PiEmbedActions CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

shared-steps: &shared-steps
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Set up Node.js
    uses: actions/setup-node@v2
    with:
      node-version: '18'
  - name: Install dependencies
    run: npm install

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - <<: *shared-steps
      - name: Run JS tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - <<: *shared-steps
      - name: Minify and Bundle the library
        run: npm run build
      - name: Upload minified version as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pi-embed-actions-build
          path: dist/pi-embed-actions-v1.0.0.min.js

  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - <<: *shared-steps
      - name: Generate JSDoc
        run: npm run generate-docs
      - name: Upload generated docs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pi-embed-actions-docs
          path: docs/